### ISSUE TITLE
APR Sources path and encoding.h

### ISSUE THREAD

**Issue by demankiller** [mikeowens/mod_ruby#1]
OS: CentOS 6.5 minimal
Apache 2.2.15
* I run `#cmake` .
* Then i try to `#make`, but it can't find APR sources.
Question is: how can i set path to it for cmake?
Package apr-devel installed and mod_ruby for apache1 makes fine.
As i noticed, `./include/apr.h` try to include `apr-1.0/*.h`, but on CentOS it has name `apr-1/*.h`
So, i correct it and `#make` again and...
face with `mod_ruby/src/ruby.cpp:2:27: error: ruby/encoding.h: No such file or directory`
So:
```
root@rabbit-6 mod_ruby]# ls ./src/ruby/
modruby  modruby.rb
```
So, where i can find encoding.h ?
`find / -regex '.*encoding.h'` puts nothing...

I see, that last commit was 7 month ago, but i can make Issue, innit?)

PS: Sorry for my english

**Comment by mikeowens** [comment]
Sorry -- I need to modify the CMakeLists.txt file to build on CentOS. For now you can edit the config/debian/settings.cmake and modify the line:

SET(APR_ROOT "apr-1.0")
to 
SET(APR_ROOT "apr-1)

And that should do it.
