### ISSUE TITLE
A few tips for those who encounter package installation problems

### ISSUE THREAD

**Issue by FSoprano** [mikeowens/mod_ruby#3]
Hi,
let me add a few notes for those who do not have Ruby installed in the assumed default location and who are less versed in the ins and outs of Linux. 
I am still a beginner, but I have done source compilations/installations before. This one here gave me a hard time. 
So I'd like to give some advice to those who want to install this package:

I installed mod_ruby on Ubuntu Linux 14.04 LTE. Apache 2 was already installed. My Ruby version is 2.2.3. 
Regarding the instructions listed here under "Building":

1. First download and unpack the mod_ruby package in a local directory.

2. Change to the highest directory in the package subtree 
(the name is probably identical with the name of the package; later on, I'll call it package directory).

3. /usr/lib/pbuilder/pbuilder-satisfydepends
I did not have pbuilder on my system, so I had to install it: sudo apt-get install pbuilder
If you run the satisfydepends command, you'll probably get a few notifications about missing packages. 
Install these as well. Then run the command again. It should exit without errors.

4. fakeroot debian/rules (from the package directory)
This one checks on all sorts of prerequisites. It'll probably terminate with an error regarding a missing variable: RUBY_INCLUDE_DIR. 
This happens if Ruby is not installed where expected. My Ruby version is in /usr/local/src. That location is different from the one assumed in the preset variables. 
Having run the fakeroot command once, you can edit the environment variables in a file called MakefileCache.txt. It's in package directory.

RUBY_INCLUDE_DIR must be set to the path in which your ruby.h file is located. This is usually a subdirectory named /include.

There are other variables that must be adapted. One points to the Ruby executable (interpreter program).
Then there are several references to libruby.a. Correct these path entries as well.

Run the command again. Make sure it terminates without errors.
Then copy the MakefileCache.txt under a different name in the same directory. You'll see why in step 5.

5. dpkg-buildpackage 
Run this command from the package directory.
I guess it does various kinds of building, but will exit with the same error as under 4:
RUBY_INCLUDE_DIR not found. This is because the command creates its own version of MakefileCache.txt, and thus 
overwrites the one you've adapted to run the fakeroot command under 4 with a fresh copy that contains the default values again.
fakeroot debian/rules seems to be executed once more as part of the dpkg-buildpackage command. Since the command will always overwrite your variable settings in MakefileCache.txt, it's no use to continue with this command. If you follow the console output, you'll see that the program fails while executing cmake . 
So this is how you should continue.

6. Rename the backup copy of MakefileCache.txt, which you saved under a different name in step 4., back to MakefileCache.txt.
Then run cmake .

7. make
This one should run without errors.

8. sudo make install
(sudo is required here because the execution requires and sets a number of permissions.).
It should also finish without errors.

I tested mod_ruby by running a small ruby script from my web browser. It worked.

I have written this information on basis of a few handwritten notes. 
So feel free to reply if I've missed something. I'am sure, however, that this information 
will be helpful if you're in the same situation.

Regards,

FSoprano

**Comment by FSoprano** [comment]
My original step numbering got messed up somehow. 1. dpkg-buildpackage should have been 
5. dpkg-buildpackage and so on.

**Comment by mikeowens** [comment]
Great job. Maybe I should actually post the documentation to this module since people are using it. I will work on it.

**Comment by FSoprano** [comment]
Thanks, Mike. Glad to hear that people find my information useful.
